INSERT INTO DOCENTES VALUES(1,'MIGUEL',25)
INSERT INTO DOCENTES VALUES(2,'JORGE',30)
INSERT INTO DOCENTES VALUES(3,'MARCELO',40)

INSERT INTO MATERIAS VALUES(1,'PROGRA-IV',1)

SELECT * FROM DOCENTES
SELECT * FROM MATERIAS

DELETE DOCENTES where idDocente=1
DELETE MATERIAS where codMateria=1

update DOCENTES SET nomDocente='juan' where idDocente=1